### ISSUE TITLE
Summary exceeds expectations

### ISSUE THREAD

**Issue by ghost** [ce-real/capstone#4]
Great job with your alt attributes, syntax, and indentation. You can add more comments. As a next step, consider adding another page to your site. In addition you can add responsive design to your buttons, so that when a buttton is clicked on, a window pops up or the button links to another page on the site. I think you're ready for it.

**Comment by ce-real** [comment]
Thank you so much for the helpful feedback throughout this course and suggestions for next steps.  I can't believe how much I've learned in such a short amount of time and am so excited to learn more as I continue on in my coding journey and try to implement your suggestions toward a better developed site.  Thanks again!
